### ISSUE TITLE
About the "get_disp"  function.

### ISSUE THREAD

**Issue by LeisureLiu** [mrharicot/monodepth#153]
Hi ! 
I am so confuse about the get_disp function in the monodepth_model.py.
I noticed that  you have  mentioned that you set d_max=0.3 in your paper, but the code seemingly just downscale the output to 0.3, am I misunderstand?  If I am not wrong , why don't just that the network learn the factor by it self?
 I have this question because  I trying to use your network to generate depth_map , and get disp by f*b/depth. But I found that if I don't multiply disp by the factor 0.3 (or lower number), the result is very bad.
Thank you, and looking forward to your answer~

**Comment by mrharicot** [comment]
Hi,
Because of the sigmoid in the get_disp function, multiplying it by 0.3 effectively brings the range to [0, 0.3].
The idea was just to limit the maximum disparity to something reasonable, in practice it shouldn't matter much.

**Comment by SamPlvs** [comment]
Hi, thanks so much for this. Forgive me for the naive questions (kinda new to this):
1. Say I'm training on a different dataset, would the scaling factor i.e. 0.3, need to be changed? I presume this works for Kitti? but maybe not others?
2. would one way be to make this scaling factor differentiable? so that we can learn it for different datasets?
3. Or would it be easier to scale this back to [0,1]?
