### ISSUE TITLE
obtain HD disparities

### ISSUE THREAD

**Issue by mokamp** [mrharicot/monodepth#21]
Is there a way of feeding say HD (1280x720) resolution images to the network and get disparities in HD format?

**Comment by mrharicot** [comment]
Not using the pretrained models.
These were trained on 256x512 images, and while the network is fully convolutional the output will not be what you expect if you feed anything that deviates too much from this size.
You would have to retrain the model using higher resolution images.
Now the last bit is that because of its depth, the current architecture only accepts input sizes that are multiples of 128 or 64 (for vgg and resnet respectively).
Training on larger sizes also takes much more time.

The easiest option is to resize the image and scale the output disparity back to the full resolution.

**Comment by mokamp** [comment]
Alright, thank you so much for clarifying!
