### ISSUE TITLE
Stereo model

### ISSUE THREAD

**Issue by milsto** [mrharicot/monodepth#35]
I am interested to know if you plan (and when) to publish the model trained on concatenated stereo image inputs which you have briefly mention in the paper (section 4.3)?

Btw, I really like this unsupervised approach to depth estimation - great work guys.

**Comment by mrharicot** [comment]
Hi,

It was mostly a toy experiment so we are did not plan on releasing it, but you can train it all the same using this code. 
I will try to upload it at some point (~ couple of months), I'll keep issue open until then.

And thank you!

**Comment by 7LFB** [comment]
hello,

thanks for your great work!!

1. when i run the code on 'do_stereo' mode,  the estimation results of  'disparities_pp.npy' is worse than 'disparities.npy':(D1-all:  84.7480 vs 9.3660). is it normal? 

2. what do you think if i using a siamese network durning the encoding to estimate the stereo image depth?

looking forward your kind advice

@mrharicot

**Comment by mrharicot** [comment]
Hi,

1. Yes, post-processing does not make sense in the stereo case. When we post-process, we evaluate the network on the image and it's mirrored version. The "skirts" or stereo disocclusion shadows will then be in on both sides of occluders. In the stereo case even if we flip the images the disocclusions will be in the same places. This is especially visible on the sides of the image, the pp stereo image will have two black borders instead of one.

2. Siamese makes sense in the monocular case, however the location of disocculsions skirts will be a problem. Not sure how you could used a siamese network for stereo though.

3. Please open a new issue instead of using an old one. :)

I hope this helps!

**Comment by mrharicot** [comment]
The stereo model, as well as the computed disparities, have finally been uploaded!
You can find them [here](http://visual.cs.ucl.ac.uk/pubs/monoDepth): `kitti_stereo`.
The results will be identical to the ones reported in the CVPR paper, Table 1.

**Comment by yxchng** [comment]
@mrharicot Do you mind explaning what does stereo disocclusion mean? It seems to be a made up term by you. It is also not explained in the paper.

**Comment by mrharicot** [comment]
https://en.wiktionary.org/wiki/disocclusion
it is not. this was the first result on google.
