### ISSUE TITLE
Cityscapes Results

### ISSUE THREAD

**Issue by jpyusiong** [mrharicot/monodepth#82]
Hi, I am wondering how you obtained the results of Cityscapes in Table 1. I check the code you provided but could not find any lines of code related to evaluating a model on the Cityscapes dataset.

**Comment by mrharicot** [comment]
Hi,
That’s because, for the row you are talking about in Table 1, we test on the 200 images from the KITTI dataset, _while_ training on only Cityscapes.
Cityscapes has a different focal and baseline from KITTI, which is why it performs so poorly.
We did not test on Cityscapes, they do not have reliable depth data.

**Comment by jpyusiong** [comment]
Got it. Thanks.
